# Where to clone the repos to
repo_dir = ""

[[package]]
# Package name (Must match the package name found in debian/control)
name = "test"

# URL to git repo (can use file:///path/to/repo for local repos)
url = "https://github.com/user/repo.git"

# Tag to build
tag = "1.0.0"
